[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Test"
authors = [{name = "kthuno", email = "kthuno@wherever"}]
dynamic = ["version", "description"]
